version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: hrm_db
    ports:
      - "5432:5432"
    # ADD THESE TWO LINES:
    volumes:
      - hr_database_data:/var/lib/postgresql/data

# ADD THESE TWO LINES AT THE ABSOLUTE BOTTOM:
volumes:
  hr_database_data: